##
## Check GETTING_STARTED.markdown for additional properties and their default
## values.
##

liferay.workspace.bundle.dist.include.metadata=true
liferay.workspace.modules.dir=modules
liferay.workspace.themes.dir=themes
liferay.workspace.wars.dir=modules
microsoft.translator.subscription.key=
liferay.workspace.product=dxp-2024.q1.5

#
# If snapshot version should be produced. Use -Psnapshot=true if you want to build a snapshot
#
snapshot=true


artifactoryUsername=
artifactoryPassword=


org.gradle.daemon=false
org.gradle.jvmargs=-Xms512m -Xmx2g
