buildscript {
    dependencies {
        classpath group: "com.liferay", name: "com.liferay.gradle.plugins.workspace", version: "10.0.3"
    }

    repositories {
        maven {
            credentials {
                username "$artifactoryUsername"
                password "$artifactoryPassword"
            }
            url "https://artifactory.vodafone.com:443/artifactory/maven-vfgvbit-csi-cove-virtual/"
        }

    }
}

apply plugin: "com.liferay.workspace"
