sonar.java.binaries=.
sonar.sourceEncoding=UTF-8
sonar.projectKey=COVE-vf-cove-middleware-api
sonar.projectName=COVE-vf-cove-middleware-api
sonar.verbose=true
sonar.exclusions=**/node_modules/**,**/OpenAPIResourceImpl.java,**Base**,**.html,**/vibe-union-scripts/**,**Test**,**-api/**,**/tests/**,**/*chunk*,**/*bundle*,**/*.test.ts,**/*.test.tsx,**/__tests__/**,**/target/**,**/build/**,**/jstransform/**,**/dist/**,**/LiberalPermissionChecker.java,**FactoryImpl**,**.yaml
sonar.host.url=https://sonarqube.vodafone.com/
sonar.cobertura.reportPath=build/reports/cobertura/coverage.xml
sonar.dynamicAnalysis=reuseReports
sonar.java.coveragePlugin=cobertura
sonar.issue.ignore.allfile=r1
sonar.issue.ignore.allfile.r1.fileRegexp=GeneratedFile
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml
